# Built-in config: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# We do not typically use/need class documentation
Documentation:
    Enabled: false

Metrics/LineLength:
  Max: 120

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'old_test/**/*'
    - 'vendor/**/*'
    - 'horowhenua_spec/**/*'
    - 'db/schema.rb'

# Not in rails 3
Rails/DynamicFindBy:
  Enabled: false

Style/FileName:
  Exclude:
    - Gemfile
    - Gemile.lock
