language: ruby
cache: bundler
bundler_args: --without development
before_install:
  - gem install bundler
rvm:
  - 2.1.2
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
  - npm install
script:
  - bundle exec rspec spec -f p
  - bundle exec rubocop
  - ./node_modules/.bin/grunt
