# Format 1: (simple gem name)
# RedCloth:

# Format 2: (source or version specific gems)
# libxml-ruby:
#   gem_name: libxml-ruby
#   lib_name: libxml
#   source: http://gems.rubyforge.org
#   version: 0.7.0

management_gems:
  capistrano:
  capistrano-ext:
  piston:
    # Currently the Github gem version of this tool isnt available
    #gem_name: francois-piston
    #lib_name: piston
    #source: http://gems.github.com

testing_gems:
  nokogiri:
  selenium-client:
    gem_name: selenium-client
    lib_name: selenium/client
  webrat:
    gem_name: brynary-webrat
    lib_name: webrat/rails
    source: http://gems.github.com
  shoulda:
    gem_name: thoughtbot-shoulda
    lib_name: shoulda/rails
    source: http://gems.github.com
  factory-girl:
    gem_name: thoughtbot-factory_girl
    lib_name: factory_girl
    source: http://gems.github.com

gems:
  packet:
  chronic:
  hpricot:
  unicode:
  RedCloth:
    gem_name: RedCloth
    lib_name: redcloth
  mime-types:
    gem_name: mime-types
    lib_name: mime/types
  memcache-client:
    gem_name: memcache-client
    lib_name: memcache
  zoom:
  libxml-ruby:
    gem_name: libxml-ruby
    lib_name: libxml
    version: 0.7.0
  feed-normalizer:
  avatar:
  htmlentities:

# we use a hacked version of oai gem for the timebeing
# included under vendor/gems
#  oai: oai

# these are problematic as gems depending on platform
# for example, rmagick on debian is best installed with
# sudo apt-get install librmagick-ruby1.8
libs:
  RMagick: RMagick

# memcached is truncated to "memcache" for compatibility with
# some systems' (Solaris10?) ps -c truncation amount
commands:
  Zebra: which zebrasrv
  Memcache Daemon: ps -Ac | grep memcache
  Unzip: which unzip
