# Format 1: (simple gem name)
# RedCloth:

# Format 2: (source or version specific gems)
# libxml-ruby:
#   gem_name: libxml-ruby
#   lib_name: libxml
#   source: http://gems.rubyforge.org
#   version: 0.7.0

management_gems:
  capistrano:
  capistrano-ext:
  capistrano-configuration:
    gem_name: kete-capistrano-configuration
    source: http://gems.github.com
  piston:
    pre_command: sudo gem uninstall francois-piston
    gem_deps: ['hoe', 'newgem', 'rubigen', 'log4r', 'main', 'mocha']
    gem_repo: git://github.com/francois/piston.git
    rake_build_gem: rake gem
    rake_install_gem: sudo rake install_gem
    lib_name: piston

testing_gems:
  webrat:
    pre_command: sudo gem uninstall brynary-webrat
    gem_deps: ['hoe', 'newgem', 'rubigen', 'log4r', 'main', 'rspec', 'nokogiri', 'selenium-client']
    gem_repo: git://github.com/brynary/webrat.git
    rake_build_gem: rake gem
    rake_install_gem: sudo rake install_gem
    lib_name: webrat
  shoulda:
    gem_name: thoughtbot-shoulda
    lib_name: shoulda/rails
    source: http://gems.github.com
  factory-girl:
    gem_name: thoughtbot-factory_girl
    lib_name: factory_girl
    source: http://gems.github.com

gems:
  nokogiri:
    pre_command: "sudo gem install hoe && sudo gem install tenderlove-frex -s http://gems.github.com && sudo gem install racc"
    gem_repo: git://github.com/kete/nokogiri.git
    rake_build_gem: rake package
    rake_install_gem: sudo gem install pkg/*.gem
    lib_name: nokogiri
  packet:
  chronic:
  hpricot:
  unicode:
  RedCloth:
    gem_name: RedCloth
    lib_name: redcloth
  mime-types:
    gem_name: mime-types
    lib_name: mime/types
  memcache-client:
    gem_name: memcache-client
    lib_name: memcache
  zoom:
  libxml-ruby:
    gem_name: libxml-ruby
    lib_name: libxml
    version: 0.7.0
  feed-normalizer:
  avatar:
  htmlentities:

# we use a hacked version of oai gem for the timebeing
# included under vendor/gems
#  oai: oai

# these are problematic as gems depending on platform
# for example, rmagick on debian is best installed with
# sudo apt-get install librmagick-ruby1.8
libs:
  RMagick: RMagick

# memcached is truncated to "memcache" for compatibility with
# some systems' (Solaris10?) ps -c truncation amount
commands:
  Zebra: which zebrasrv
  Memcache Daemon: ps -Ac | grep memcache
  Unzip: which unzip
